version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:5173"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/app
    env_file:
      - .env  

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"